// Build pipeline: DTCG JSON → CSS custom properties.
//
// Output:
//   dist/theme.css         Tailwind v4 @theme with primitives + semantic defaults
//   dist/brands/ecru.css   Scoped semantic overrides for [data-brand="ecru"][data-theme=light|dark]
//   dist/tokens.json       Flat DTCG bundle (for Figma / other tools)
//
// Keeps Style Dictionary doing token resolution, then post-processes to the
// @theme / scoped shape Tailwind v4 expects.

import StyleDictionary from "style-dictionary";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const dist = resolve(root, "dist");
mkdirSync(resolve(dist, "brands"), { recursive: true });

const BRANDS = ["ecru"];
const MODES = ["light", "dark"];

// ─────────────────────────────────────────────────────────────────────────────
// 1. Resolve primitives once (palettes, space, radius, typography).
// ─────────────────────────────────────────────────────────────────────────────
const primitivesSD = new StyleDictionary({
  source: [resolve(root, "src/primitives/**/*.json")],
  platforms: {
    css: {
      transformGroup: "css",
      files: [{ destination: "primitives.css", format: "css/variables", options: { selector: ":root" } }]
    }
  }
});
await primitivesSD.buildAllPlatforms();

// ─────────────────────────────────────────────────────────────────────────────
// 2. For each brand × mode, resolve semantic layer against primitives.
// ─────────────────────────────────────────────────────────────────────────────
const brandOutputs = {};
for (const brand of BRANDS) {
  brandOutputs[brand] = {};
  for (const mode of MODES) {
    const sd = new StyleDictionary({
      source: [
        resolve(root, "src/primitives/**/*.json"),
        resolve(root, `src/brands/${brand}/${mode}.json`)
      ],
      platforms: {
        css: {
          transformGroup: "css",
          buildPath: `dist/_tmp-${brand}-${mode}/`,
          files: [{ destination: "resolved.css", format: "css/variables", options: { selector: ":root" } }]
        }
      }
    });
    await sd.buildAllPlatforms();
    const raw = readFileSync(resolve(root, `dist/_tmp-${brand}-${mode}/resolved.css`), "utf8");
    brandOutputs[brand][mode] = extractSemantic(raw);
  }
}

// Only keep --color-{bg,fg,border,accent,status,focus}-* — these are the semantic layer.
function extractSemantic(css) {
  return css
    .split("\n")
    .filter((l) => /^\s*--color-(bg|fg|border|accent|status|focus)/.test(l))
    .join("\n");
}

// Primitives CSS, rewritten as @theme for Tailwind v4.
const primitivesRaw = readFileSync(resolve(dist, "primitives.css"), "utf8");
const primitiveVars = primitivesRaw
  .split("\n")
  .filter((l) => /^\s*--/.test(l))
  .map((l) => "  " + l.trim())
  .join("\n");

// ─────────────────────────────────────────────────────────────────────────────
// 3. Emit dist/theme.css — the single file Tailwind and apps import.
// ─────────────────────────────────────────────────────────────────────────────
const defaultBrand = BRANDS[0];
const header = `/* Generated by @ecru/tokens — do not edit by hand. */\n`;

const themeCss = [
  header,
  `@theme {`,
  primitiveVars,
  `}`,
  ``,
  `/* Default brand: ${defaultBrand} / light. Applied at :root. */`,
  `:root, [data-brand="${defaultBrand}"][data-theme="light"] {`,
  brandOutputs[defaultBrand].light,
  `}`,
  ``,
  `[data-brand="${defaultBrand}"][data-theme="dark"], .dark {`,
  brandOutputs[defaultBrand].dark,
  `}`,
  ``
].join("\n");

writeFileSync(resolve(dist, "theme.css"), themeCss);

// Per-brand standalone CSS (for consumers who want to scope a subtree to a brand).
for (const brand of BRANDS) {
  const brandCss = [
    header,
    `[data-brand="${brand}"][data-theme="light"] {`,
    brandOutputs[brand].light,
    `}`,
    ``,
    `[data-brand="${brand}"][data-theme="dark"] {`,
    brandOutputs[brand].dark,
    `}`,
    ``
  ].join("\n");
  writeFileSync(resolve(dist, `brands/${brand}.css`), brandCss);
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. Tiny JS entry so consumers can `import { brands } from "@ecru/tokens"`.
// ─────────────────────────────────────────────────────────────────────────────
writeFileSync(
  resolve(dist, "index.js"),
  `export const brands = ${JSON.stringify(BRANDS)};\nexport const modes = ${JSON.stringify(MODES)};\n`
);
writeFileSync(
  resolve(dist, "index.d.ts"),
  `export declare const brands: readonly ${BRANDS.map((b) => `"${b}"`).join(" | ")}[];\nexport declare const modes: readonly ("light" | "dark")[];\n`
);

console.log(`✓ tokens built → ${dist}`);
